spring:
  application:
    name: endpoint-with-sql
  datasource:
    url: jdbc:postgresql://sloth-2.suslovd.ru:9132/endpoint
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
auth:
  login: endpoint2
  password_hash: $2a$12$ONebYb21q/BIEbQfZNT5ieIBEEhoZWZTnp6Jvwk.fpf4J/NgPUHDm